name: Release

on:
  workflow_dispatch:
  repository_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2

    - name: do build
      run: cd src;./release_macos.sh

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build/artifact/loginsight.dmg
